### PR TITLE
Document how to track component arguments

### PR DESCRIPTION
**Pull request by asakusuma**

### CODE REVIEW

**Comment by locks** [comment]
This sounds like something the lifecycle hooks would be useful for, when we have them ;P
@tomdale can you validate this is something we want users to do meanwhile?

**Comment by tomdale** [comment]
Nice work @asakusuma! 👍  @locks Your comment is from March but AFAIK we have all the lifecycle hooks we need. Do you remember what you meant by this?

**Comment by locks** [comment]
@tomdale not anymore :X

**Comment by tomdale** [comment]
@locks The lifecycle hooks in Glimmer seem anemic because there are only `did*` hooks, not `will*` hooks. But this is actually by design: it cuts the amount of arbitrary user code we need to invoke in half. Our hypothesis is that anything that you would do in e.g. `willRender` can be modeled with a more performant "pull" model in tracked computed properties. I want to update the documentation to note this so it's clear it's a design decision and not just missing functionality.

**Pull request merged**
