### PR TITLE
[DOC] make homepage reference NPM to be consistent with emberjs.com

### PR DESCRIPTION
**Pull request by sclatter**
Wanting to normalize more between Emberjs.com doc and Glimmerjs.com doc. @rwjblue recommended moving this one to conform rather than the other way around.

### CODE REVIEW

**Comment by locks** [comment]
We were hoping that `yarn global add` problems would be small enough that we could power through it and not lose people in the process, but it's proving to be more widespread.
Thanks for the contribution @sclatter, we'll revisit this after we help yarn figure out the problem.

**Comment by tomdale** [comment]
Ack, this is actually a regression! Users need to be using the canary version of Ember CLI so blueprints from npm work. (`npm install ember-cli/ember-cli`)

**Comment by sclatter** [comment]
@tomdale will send another PR this am - sorry I missed the nuance if canary!

**Comment by acorncom** [comment]
@sclatter Looks like Tom got it already, thanks!

**Pull request merged**
